# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 459dfb4f80df6510bff73f0ba9ac0b17176d8c69db9261578098be459923fb19c3dc07030729146a53b1c11fdafe3da2693d6e44ac96c1ee96c9b91c889ab7fa

test:
  secret_key_base: e0dbc0fc0bbc565a14846b701058b42426002e2a64f11306c00850767275af2ffca5ca9da6d92d3280e6ff9404d89c1efa4cc4eb63637480a0b970e5216b539c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
